name: My English University
favicon: null
layout_spectrum: 0.65703
typography_spectrum: 0.4123001336120069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#204a7c'
    - '#4275aa'
    - '#fdd252'
    - '#56524e'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3542456526774913
  rhythmicContrast: 0.5
purpose: []
